### PR TITLE
Replace V1/V2 distinction with two command modes

### PR DESCRIPTION
**Pull request by rti**
On Debian Stretch, LXC 2 still uses the multiple command system like LXC 1, e.g. ```lxc-info```, ```lxc-attach``` and alike. Therefor I renamed the distinction.

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
@rti Do you plan to work around the versioning issue I mentioned above?

**Comment by psychedelys** [comment]
Just to answers your question:

$ lxc-ls --version 
2.0.7

But I find it more a cosmetic issue, than a real one. And I fully understood @andreasscherbaum comment about room for improvident, who know what will be v3.

**Comment by andreasscherbaum** [comment]
Haven't seen any activity on this PR. The PR does not include any functionality beyond using another flag for the commands.

**Comment by rti** [comment]
Hi,

just found some interesting information shading more light on the misunderstanding we had two years ago.

> lxd
> lxd is the LXD daemon. [...]
> The lxc command is the LXD front-end (“LXD Client” is how I think of it).
>
> lxc
> LXC commands start with lxc- (that’s lxc followed by a short hyphen). If there’s no hyphen, just the literal command lxc, that’s 
associated with LXD.

https://discuss.linuxcontainers.org/t/comparing-lxd-vs-lxc/24


> The packaging in Ubuntu is a bit confusing unfortunately...
> "lxc1" is the "LXC 1.0 user experience" which is what normal people call LXC
> "lxc2" is the "LXC 2.0 user experience" which is what normal people call LXD
> So if you install "lxc1", you'll get the usual LXC tools "lxc-create/lxc-start/..." and all of those will be at version 2.0.7, [...]

https://lists.linuxcontainers.org/pipermail/lxc-users/2017-April/013083.html

So, ansible-lxc-ssh's version mechanism is actually mirroring a confusing Ubuntu package naming scheme. IMHO, the distinction made by ansible-lxc-ssh should actually be "lxc (using lxc-* tools) vs. lxd (using lxc client tool)". Also, definitely, there should be support for version dependent differences in both of those systems.

BTW, I am nowadays running Debian 10. lxd with lxc as command line client tool did not make it into Debian yet, see https://wiki.debian.org/LXD .

```
$ lxc-ls --version
3.0.3
$ lxc
-bash: lxc: command not found
```
This still renders this pull request non-sense. I just wanted to share what I just learned. 

Cheers

**Comment by andreasscherbaum** [comment]
Thanks for the update!

I agree that any PR should take multiple versions (>2) into account. This way the plugin can be backwards compatible.

**Pull request closed without merging**
