### PR TITLE
Add lxc_container option and documentation

### PR DESCRIPTION
**Pull request by dmp1ce**

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
How can this be tested?

**Comment by AnvithLobo** [comment]
https://github.com/andreasscherbaum/ansible-lxc-ssh/issues/37#issuecomment-858932351

https://github.com/AnvithLobo/ansible-lxc-ssh

I've written a test for it now feel free to refactor adopt it how you see fit for this project.

**Comment by andreasscherbaum** [comment]
@dmp1ce Can you please rebase and push this PR, to fire the new tests again? Thanks.

**Comment by dmp1ce** [comment]
> @dmp1ce Can you please rebase and push this PR, to fire the new tests again? Thanks.

👍

**Comment by stefangweichinger** [comment]
Ah, yes, I just wanted to vote for merging this one as well. Looks good also.

**Pull request merged**
