### PR TITLE
Fix fetch for Python3

### LINKED ISSUE #23: Fetch task fails
Fetch task fails for me. Could this be another Python3 issue?

```
    - name: My backup task
      fetch:
        src: /tmp/myfile-{{ ansible_date_time.date }}.tar.gz
        dest: localbackups
```

```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 144, in run
    res = self._execute()
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 648, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python3.7/site-packages/ansible/plugins/action/fetch.py", line 172, in run
    self._connection.fetch_file(source, dest)
  File "/home/david/Workspace/UpgradeYa/albatross-ansible/connection_plugins/lxc_ssh.py", line 1245, in fetch_file
    out_f.write(stdout)
TypeError: write() argument must be str, not bytes

fatal: [omd]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

### PR DESCRIPTION
**Pull request by dmp1ce**
Fixes #23

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
I agree with the change. Can you please include the other open() a few lines above as well? Just to have the same code everywhere.

Thanks,
Andreas!

**Comment by dmp1ce** [comment]
I can but I don't think people running Ansible version < 2.3 will be using Python3 because at that version it was Python3 wasn't fully supported. https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html

**Comment by andreasscherbaum** [comment]
2.3 is no longer supported, I see:
https://access.redhat.com/support/policy/updates/ansible-engine

Should probably remove all the code for it.

**Comment by dmp1ce** [comment]
Yes, I agree with removing code for 2.3.

**Pull request merged**
