### PR TITLE
[WIP]fix upload of binary data with ansible copy module in python3

### PR DESCRIPTION
**Pull request by TuxCoder**
this is not tested with python2 but it should work

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
@TuxCoder Wouldn't it make sense to use "wb" in fetch_file() as well?

**Comment by TuxCoder** [comment]
@andreasscherbaum Thanks for the review, of course it makes sense, only not run into that issue :)

will update the PR

**Comment by TuxCoder** [comment]
updated the code but not sure about handling, because
fd=open('<path>','wb')
fd.write(b'..') # requeires binary string

**Comment by andreasscherbaum** [comment]
Ifit's not a binary object, then Python (at least on Windows) might adjust for line endings, right?

**Comment by TuxCoder** [comment]
probably I will add a check, if data type is binary use 'wb' else 'w'.

I think we can read always binary?
Because the amount of windows user should be not so big

currently I have no other Idea

**Comment by andreasscherbaum** [comment]
@TuxCoder What I meant is that if you don't use binary, Python on Windows might "adjust" the line endings for you in text files. Usually you don't want that, but you want to copy the file 1:1 instead. That's why "binary mode" should be a good change here, in both ways.

**Comment by andreasscherbaum** [comment]
@TuxCoder Is this PR still WIP?

**Pull request closed without merging**
