### PR TITLE
refactored with black, for PEP8

### PR DESCRIPTION
**Pull request by stefangweichinger**
The [debops](https://docs.debops.org/en/master/) project uses your connection plugin for their debops.lxc ansible role.

We saw the PR https://github.com/andreasscherbaum/ansible-lxc-ssh/pull/31 and plan to port the resulting new plugin over to debops.

The main dev of debops told me to make the plugin PEP8-compatible, so I ran it through a PEP8-compliant formatter.

I know of the rejected PR https://github.com/andreasscherbaum/ansible-lxc-ssh/pull/15, and we fully understand the priority of readability for the coder. Pls review if the suggested changes work for you. To me the diff looks as if it just fixes/changes some formatting, but doesn't move stuff around.

Regards, Stefan

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
Looks indeed as if you only change the formatting, and I can live with that.
Regression tests also pass. I'm going to merge this.

Thanks for the PR!

**Comment by stefangweichinger** [comment]
> Looks indeed as if you only change the formatting, and I can live with that.
> Regression tests also pass. I'm going to merge this.
> 
> Thanks for the PR!

You're welcome. I will work on porting your script to the debops.lxc role in the next days. Thanks as well.

**Comment by stefangweichinger** [comment]
Would you accept more reformatting?

As to be seen [here](https://github.com/debops/debops/pull/1714/checks?check_run_id=2620989951) a check against `pycodestyle` shows quite a few suggestions, mostly too long lines.

**Comment by andreasscherbaum** [comment]
@stefangweichinger I spotted a few outdated comments, and removed them.
In general if you separate formatting and code changes, this is not a problem.
If you start modifying code and hide this in a larger "code cleanup", I might have strong objections.

**Comment by stefangweichinger** [comment]
@andreasscherbaum Thanks for your reply. No worries, I am no python coder myself, I only help at porting the script ... so this will only be formatting in the first run. The `debops` project runs high standards, and tests for PEP8 conformity using `pycodestyle`.

I will try to reformat comments and long lines to get rid of most of the warnings. If things touch actual code, I will ask you for help and decisions. It's your script/plugin after all!

Do you want me to open another PR for the next steps? have a nice evening ...

**Comment by andreasscherbaum** [comment]
@stefangweichinger Another PR makes sense, yes.

**Comment by stefangweichinger** [comment]
> @stefangweichinger Another PR makes sense, yes.

I agree. I try to come up with a first set of changes asap.

**Pull request merged**
