### PR TITLE
Adapt the plugin for Ansible 2.4

### PR DESCRIPTION
**Pull request by lgeorget**
Hello!

I did a 3-way merge between your lxc-ssh.py and Ansible 2.4 ssh.py connection plugin (the lxc-ssh.py plugin by Pierre Chifflier chifflier/ansible-lxc-ssh is originally derived from the Ansible 2.2 ssh connection plugin) and came up with this new version of the plugin which works with Ansible 2.4. It's highly experimental but working for me so far.

I think it breaks compatibility with previous versions of Ansible so we should probably keep both versions of the plugin and have a clear versioning, or an autodetection of Ansible version.

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
Wow, that's quite a large patch!

I'd love to merge it in, but also not break compatibility with older versions, who will surely be around for quite a while. I also do not have (yet) a 2.4 installation around to test it.

Any chance you can do a version detection, and make it compatible with both 2.2 and 2.4?

**Comment by lgeorget** [comment]
I'm not really a seasoned python developer but I can try. I guess the easier way would be to make two modules (like lxc-ssh-2.2.py and lxc-ssh-2.4.py) and then have a lxc-ssh.py which would load one or the other.

**Comment by andreasscherbaum** [comment]
Then you have to pass down arguments and such, check that both modules are installed.

How about you split that huge patch into several chunks instead. One can be the documentation update, that probably takes away 30-40% of the changes.

**Comment by lgeorget** [comment]
Ok, I'll try that.

**Comment by andreasscherbaum** [comment]
Any luck with this patch?

**Comment by andreasscherbaum** [comment]
As mentioned in #6, I adapted this patch and made it work with Ansible 2.3, 2.4 and lower versions.

Thanks for your excellent work in this PR, that was the groundwork to actually make it work!

**Comment by lgeorget** [comment]
Ups... I had completely forgotten about that... Sorry to have left you all the work :/

**Pull request closed without merging**
