### PR TITLE
Fix issues found by pyCodeStyle

### PR DESCRIPTION
**Pull request by drybjed**
The script was scanned by `pyCodeStyle` and all issues with linting and code style have been fixed. There shouldn't be any changes with functionality.

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
I'm ok with reformatting code. I'm not ok with moving code around, or moving my comments from where I placed them to where a script thinks they should be. There are reasons I placed them where they are.

**Comment by drybjed** [comment]
@andreasscherbaum Should I create another PR with just formatting changes split into small commits for cherry-picking?

**Comment by andreasscherbaum** [comment]
@drybjed If there are just formatting changes, yes. Please avoid moving code around, or move comments.

I know that my comment style does not fit whatever the current language is requesting, and they are all different. I just add comments the way I can understand them later.

**Comment by drybjed** [comment]
@andreasscherbaum Sure, I understand that. I'm happy to keep the fork updated in my project. I'll prepare a new PR with the changes in a few days, as time permits.

**Pull request closed without merging**
