### PR TITLE
Add nested lxc test to fully test the lxc_ssh.py plugin from ssh to lxc

### PR DESCRIPTION
**Pull request by dmp1ce**
Add nested lxc test thanks to the work of @AnvithLobo. This should fully test the lxc_ssh.py plugin.

I'm not sure the previous tests were testing lxc_ssh.py at all to be honest.

### CODE REVIEW

**Comment by AnvithLobo** [comment]
is there any reason to have this test ? 
https://github.com/andreasscherbaum/ansible-lxc-ssh/blob/3e378a4a5f4a2a9da62ffe733f401ffc4b2803c5/tests/test-lxc_ssh.yml#L50-L94
Since `asible_user` is by default `root` when you attach lxc. So `become: yes` / `become: yes` should not have any different effect here

**Comment by dmp1ce** [comment]
I'm not sure. Does `become` do anything with the plugin?

**Comment by AnvithLobo** [comment]
> I'm not sure. Does `become` do anything with the plugin?

nope nothing since the default container user is root when you exec commands with lxc . I'm not yet sure if become_user works either. Still have to test that

**Comment by dmp1ce** [comment]
Well, I'm happy to remove it or leave it in for future use.

**Comment by dmp1ce** [comment]
I removed the `become: no` section.

**Comment by andreasscherbaum** [comment]
@dmp1ce All the new tests are failing with ssh key problem.

**Comment by dmp1ce** [comment]
> @dmp1ce All the new tests are failing with ssh key problem.

That's right! Because the tests from this PR correctly show the state of lxc_ssh plugin. The #41 PR fixed the plugin so the tests pass.

**Comment by andreasscherbaum** [comment]
Based on discussion [here](https://github.com/andreasscherbaum/ansible-lxc-ssh/pull/38#issuecomment-891020319) I'm going to merge this PR, and then re-test #38.

**Pull request merged**
